//go:build !ignore_autogenerated

// Copyright 2025 Nutanix. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLicenseStatus) DeepCopyInto(out *NodeLicenseStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLicenseStatus.
func (in *NodeLicenseStatus) DeepCopy() *NodeLicenseStatus {
	if in == nil {
		return nil
	}
	out := new(NodeLicenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPULicenseValidator) DeepCopyInto(out *VGPULicenseValidator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPULicenseValidator.
func (in *VGPULicenseValidator) DeepCopy() *VGPULicenseValidator {
	if in == nil {
		return nil
	}
	out := new(VGPULicenseValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VGPULicenseValidator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPULicenseValidatorList) DeepCopyInto(out *VGPULicenseValidatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VGPULicenseValidator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPULicenseValidatorList.
func (in *VGPULicenseValidatorList) DeepCopy() *VGPULicenseValidatorList {
	if in == nil {
		return nil
	}
	out := new(VGPULicenseValidatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VGPULicenseValidatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPULicenseValidatorSpec) DeepCopyInto(out *VGPULicenseValidatorSpec) {
	*out = *in
	if in.LicenseVerificationImage != nil {
		in, out := &in.LicenseVerificationImage, &out.LicenseVerificationImage
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CheckIntervalDuration != nil {
		in, out := &in.CheckIntervalDuration, &out.CheckIntervalDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.InitialDelayDuration != nil {
		in, out := &in.InitialDelayDuration, &out.InitialDelayDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPULicenseValidatorSpec.
func (in *VGPULicenseValidatorSpec) DeepCopy() *VGPULicenseValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(VGPULicenseValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPULicenseValidatorStatus) DeepCopyInto(out *VGPULicenseValidatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeLicenseStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPULicenseValidatorStatus.
func (in *VGPULicenseValidatorStatus) DeepCopy() *VGPULicenseValidatorStatus {
	if in == nil {
		return nil
	}
	out := new(VGPULicenseValidatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPUToken) DeepCopyInto(out *VGPUToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPUToken.
func (in *VGPUToken) DeepCopy() *VGPUToken {
	if in == nil {
		return nil
	}
	out := new(VGPUToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VGPUToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPUTokenList) DeepCopyInto(out *VGPUTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VGPUToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPUTokenList.
func (in *VGPUTokenList) DeepCopy() *VGPUTokenList {
	if in == nil {
		return nil
	}
	out := new(VGPUTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VGPUTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPUTokenSpec) DeepCopyInto(out *VGPUTokenSpec) {
	*out = *in
	out.TokenSecret = in.TokenSecret
	if in.HostDirectoryPath != nil {
		in, out := &in.HostDirectoryPath, &out.HostDirectoryPath
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPUTokenSpec.
func (in *VGPUTokenSpec) DeepCopy() *VGPUTokenSpec {
	if in == nil {
		return nil
	}
	out := new(VGPUTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VGPUTokenStatus) DeepCopyInto(out *VGPUTokenStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VGPUTokenStatus.
func (in *VGPUTokenStatus) DeepCopy() *VGPUTokenStatus {
	if in == nil {
		return nil
	}
	out := new(VGPUTokenStatus)
	in.DeepCopyInto(out)
	return out
}
