# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: vgpu-token-operator
description: A Helm chart to distribute the project vgpu-token-operator
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: "https://example.com/icon.png"
maintainers:
- name: faiq
  email: faiqrazarizvi@gmail.com
  url: nutanix.com
