{{- if and .Values.rbac.enable .Values.metrics.enable }}
# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: vgpu-token-operator-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
{{- end -}}
