# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nkp.nkp.nutanix.com
  resources:
  - vgpulicensevalidators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nkp.nkp.nutanix.com
  resources:
  - vgpulicensevalidators/finalizers
  verbs:
  - update
- apiGroups:
  - nkp.nkp.nutanix.com
  resources:
  - vgpulicensevalidators/status
  verbs:
  - get
  - patch
  - update
