{{- if .Values.rbac.enable }}
# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# This rule is not used by the project vgpu-token-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nkp.nkp.nutanix.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: vgputoken-admin-role
rules:
- apiGroups:
  - nkp.nkp.nutanix.com
  resources:
  - vgputokens
  verbs:
  - '*'
- apiGroups:
  - nkp.nkp.nutanix.com
  resources:
  - vgputokens/status
  verbs:
  - get
{{- end -}}
