# Copyright 2021-2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write
  actions: write

defaults:
  run:
    shell: bash

jobs:
  release-tag:
    runs-on:
      - self-hosted-ncn-docker-medium
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          skip-nix-installation: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        run: devbox run -- make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OCI_REPOSITORY: ghcr.io/nutanix-cloud-native

      - name: Package Helm chart and attach to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OCI_REPOSITORY: ghcr.io/nutanix-cloud-native
        run: |
          devbox run -- helm package ./charts/vgpu-token-operator \
                          --destination . \
                          --version ${{ github.ref_name }} \
                          --app-version ${{ github.ref_name }}
          devbox run -- gh release upload ${{ github.ref_name }} vgpu-token-operator-*.tgz
